version: "3.7"

services:

  backend:
    depends_on:
      - db
    build: ./backend
    environment:
      DB_HOST: db:3306
      DB_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    labels:
      traefik.enable: true
      traefik.backend: "flask"
      traefik.frontend.rule: PathPrefix:/api
      traefik.port: '80'
      traefik.flask.weight: 10

  frontend:
    build: 
      context: ./frontend
      args:
          FRONTEND_ENV: ${FRONTEND_ENV-production}
    restart: always
    environment:
      TZ: Asia/Ho_Chi_Minh
    labels:
      traefik.enable: true
      traefik.backend: "nuxt"
      traefik.frontend.rule: PathPrefix:/
      traefik.frontend.rule: Host:${API_HOST}
      traefik.port: '3000'
      traefik.nuxt.weight: 1

  db:
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro

  traefik:
    image: traefik:1.7
    command:
      - --logLevel=INFO
      - --accessLog.filePath=/var/log/traefik/access.log
      - --traefikLog.filePath=/var/log/traefik/traefik.log
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/traefik.toml:/etc/traefik/traefik.toml:ro
      - ./traefik/acme:/etc/traefik/acme
      - ./traefik/logs:/var/log/traefik
    ports:
     - "80:80"
     - "443:443"
