defaultEntryPoints = ["https","http"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
  [entryPoints.https.tls]

[retry]

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "airvisual.sun-asterisk.vn"
watch = true
exposedByDefault = false

[acme]
email = "admin@sun-asterisk.vn"
caServer = "https://acme-staging-v02.api.letsencrypt.org/directory"
storage = "acme.json"
entryPoint = "https"
onHostRule = true

[acme.httpChallenge]
  entryPoint = "http"

[[acme.domains]]
  main = "airvisual.sun-asterisk.vn"
