
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-air-viewer
  labels:
    app: backend-air-viewer
  namespace: air-viewer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-air-viewer
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: backend-air-viewer
    spec:
      containers:
      - image: quanghung97/backend-air-viewer:v1
        imagePullPolicy: Always
        name: backend-air-viewer
        env:
          - name: DB_HOST
            value: mysql:3306
          - name: DB_DATABASE
            value: air_viewer
          - name: DB_USERNAME
            value: example
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-pass-non-root
                key: ROOT_PASSWORD
        ports:
        - containerPort: 80
          protocol: TCP
