apiVersion: v1
kind: Service
metadata:
  name: backend-air-viewer
  namespace: air-viewer
  labels:
    app: backend-air-viewer
spec:
  selector:
    app: backend-air-viewer
  ports:
   -  protocol: TCP
      port: 80
      targetPort: 80
