apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-air-viewer
  labels:
    app: frontend-air-viewer
  namespace: air-viewer
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend-air-viewer
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: frontend-air-viewer
    spec:
      containers:
      - image: quanghung97/frontend-air-viewer:framgia2c
        imagePullPolicy: Always
        name: frontend-air-viewer
        ports:
        - containerPort: 3000
          protocol: TCP
        env:
        - name: TZ
          value: Asia/Ho_Chi_Minh
