 
apiVersion: v1
kind: Service
metadata:
  name: frontend-air-viewer
  namespace: air-viewer
  labels:
    app: frontend-air-viewer
spec:
  selector:
    app: frontend-air-viewer
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
